# Generated by Django 3.1.3 on 2021-06-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('F', 'Fruit'), ('V', 'Vegetables'), ('M', 'meat')], default='F', max_length=10),
            preserve_default=False,
        ),
    ]
