# Generated by Django 3.1.3 on 2021-06-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fruit', 'Fruit'), ('Vegetables', 'Vegetables'), ('Meat', 'Meat')], max_length=10),
        ),
    ]
